name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: "github.com/JWhist/*"
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache: false
      - uses: actions/checkout@v3
      - run: git config --global url."https://${{secrets.GITHUB_TOKEN}}:x-oauth-basic@github.com/"".insteadOf "https://github.com/""
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
