name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: "github.com/JWhist/*"
      CGO_ENABLED: 0
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true
      - run: git config --global url."https://${{secrets.GITHUB_TOKEN}}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@latest
        with:
          version: latest
