name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: "github.com/JWhist/*"
      CGO_ENABLED: 0
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true
      - run: git config --global url."ssh@github.com/JWhist".insteadOf "https://github.com/JWhist"
      - name: Give GitHub Actions access to private repository
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PRIV_TOKEN }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.6.0
        with:
          version: latest
